/*
SELECT * FROM ATIVIDADE;

SELECT * FROM DEPARTAMENTO;

SELECT * FROM FUNCIONARIO;

SELECT * FROM HISTORICO_PROMOCAO;

SELECT * FROM PROJETO;

SELECT * FROM PROJETO_ATIVIDADE;
*/

/*
SELECT CD_GERENTE FROM DEPARTAMENTO
WHERE CD_DEPTO = 'HR';

SELECT TX_DESCRICAO FROM ATIVIDADE
WHERE CD_ATIV = 3;

SELECT NM_FUNC, NM_SOBRENOME, CD_DEPTO, NR_RAMAL, VL_SAL FROM FUNCIONARIO
WHERE CD_MAT = 1001;
*/

